### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by cjszhj** [apm1467/videocr#17]
OS: fedora 31
Python: 3.7
代码：
from videocr import get_subtitles
if __name__ == '__main__':  # This check is mandatory for Windows.
    print(get_subtitles('22.mp4', lang='chi_sim+eng', sim_threshold=70, conf_threshold=65,use_fullframe=False))

执行后cpu满载运行，提示:
`Traceback (most recent call last):
  File "t.py", line 8, in <module>
    print(get_subtitles('22.mp4', lang='chi_sim+eng', sim_threshold=70, conf_threshold=65))
  File "/usr/local/lib/python3.7/site-packages/videocr/api.py", line 11, in get_subtitles
    v.run_ocr(lang, time_start, time_end, conf_threshold, use_fullframe)
  File "/usr/local/lib/python3.7/site-packages/videocr/video.py", line 52, in run_ocr
    for i, data in enumerate(it_ocr)
  File "/usr/local/lib/python3.7/site-packages/videocr/video.py", line 52, in <listcomp>
    for i, data in enumerate(it_ocr)
  File "/usr/local/lib/python3.7/site-packages/videocr/models.py", line 32, in __init__
    block_num, conf = int(block_num), int(conf)
ValueError: invalid literal for int() with base 10: '-'

**Comment by usernamecannotbeempty** [comment]
This problem is resolved in [this thread](https://github.com/apm1467/videocr/issues/28).
