### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by oregonpillow** [apm1467/videocr#36]
```
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    print(get_subtitles(video, lang='chi_sim+eng', sim_threshold=70, conf_threshold=65))
  File "/home/ubuntu/Github/videocr/env/lib/python3.8/site-packages/videocr/api.py", line 8, in get_subtitles
    utils.download_lang_data(lang)
  File "/home/ubuntu/Github/videocr/env/lib/python3.8/site-packages/videocr/utils.py", line 21, in download_lang_data
    with urlopen(url) as res, open(filepath, 'w+b') as f:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

not sure why this is happening. I'm guessing it's a version problem. Trying to run the example code with my own video (full system path specified)

@apm1467  Any chance you could provide the exact python version, tesseract version you used successfully?

**Comment by Mschul** [comment]
I am facing to exact same problem. I also tried fixing the urls referenced in constants.py
`TESSDATA_URL = 'https://github.com/tesseract-ocr/tessdata_fast/raw/master/{}.traineddata'`
`TESSDATA_SCRIPT_URL = 'https://github.com/tesseract-ocr/tessdata_best/raw/master/script/{}.traineddata'`
since paths changed, but didnt solve the problem.

**Comment by Mageikk** [comment]
I had the same issue, and I don't know how to fix the automated download. However, if you simply go to `https://github.com/tesseract-ocr/tessdata_best` or `https://github.com/tesseract-ocr/tessdata_fast`, manually download the language files you need (so when in doubt just get all of them) and put them into the folder also referenced in constants.py you will not need the automated download anymore. Not perfect, but good enough for me

**Comment by hw-lunemann** [comment]
I ran into the same issue and putting

TESSDATA_URL = 'https://github.com/tesseract-ocr/tessdata_fast/blob/main/{}.traineddata?raw=true'

TESSDATA_SCRIPT_URL = 'https://github.com/tesseract-ocr/tessdata_best/blob/main/{}.traineddata?raw=true'

in constants.py fixes the downloading issue!

**Comment by m-ziglioli** [comment]
@hadis-git are you sure? it still gives me error.
substituting {} with the language needed worked.

**Comment by hw-lunemann** [comment]
Yes, I am sure,
The lang parameter in https://github.com/apm1467/videocr/blob/9b97c996570897b5a45d1f8b4f046aebcbcca300/videocr/api.py#L5 is split by '+', substituted into those constants. Then the models are downloaded here
https://github.com/apm1467/videocr/blob/9b97c996570897b5a45d1f8b4f046aebcbcca300/videocr/utils.py#L9

So you have to make sure that your lang parameter corresponds to one or more of the available models.

**Comment by hw-lunemann** [comment]
What's the error you get?

**Comment by m-ziglioli** [comment]
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    videocr.save_subtitles_to_file('out.mkv', lang='dan')
  File "C:\Users\CrisMattGiov\AppData\Roaming\Python\Python38\site-packages\videocr\api.py", line 20, in save_subtitles_to_file
    f.write(get_subtitles(
  File "C:\Users\CrisMattGiov\AppData\Roaming\Python\Python38\site-packages\videocr\api.py", line 8, in get_subtitles
    utils.download_lang_data(lang)
  File "C:\Users\CrisMattGiov\AppData\Roaming\Python\Python38\site-packages\videocr\utils.py", line 21, in download_lang_data
    with urlopen(url) as res, open(filepath, 'w+b') as f:
  File "C:\Program Files\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by hw-lunemann** [comment]
Well, it's telling you that the url to the language models is wrong.
How about you `print(url)` out that url right here?
https://github.com/apm1467/videocr/blob/9b97c996570897b5a45d1f8b4f046aebcbcca300/videocr/utils.py#L20

Then you'll see if you edited the right constants.py

**Comment by hsnfirdaus** [comment]
This is because the branch name of [tessdata_fast](https://github.com/tesseract-ocr/tessdata_fast) and [tessdata_best](https://github.com/tesseract-ocr/tessdata_best) changed from master to main, so the URL in file [videocr/constants.py](../blob/master/videocr/constants.py) must changed, from :
```python
TESSDATA_URL = 'https://github.com/tesseract-ocr/tessdata_fast/raw/master/{}.traineddata'

TESSDATA_SCRIPT_URL = 'https://github.com/tesseract-ocr/tessdata_best/raw/master/script/{}.traineddata'
```
to
```python
TESSDATA_URL = 'https://github.com/tesseract-ocr/tessdata_fast/raw/main/{}.traineddata'

TESSDATA_SCRIPT_URL = 'https://github.com/tesseract-ocr/tessdata_best/raw/main/script/{}.traineddata'
```
we must wait for owner of this repository fix this issue, otherwise if you want to change it yourself, change this file in your pip library installation directory, in linux if you install using pip the directory is `~/.local/lib/python{version}/site-packages/videocr/` or  `/usr/local/lib/python{version}/dist-packages` check in google for other OS.

**Comment by xiaoliwang** [comment]
> It should move
> 
> ```python
> TESSDATA_URL = 'https://github.com/tesseract-ocr/tessdata_fast/raw/master/{}.traineddata'
> 
> TESSDATA_SCRIPT_URL = 'https://github.com/tesseract-ocr/tessdata_best/raw/master/script/{}.traineddata'
> ```
> 
> to
> 
> ```python
> TESSDATA_URL = 'https://github.com/tesseract-ocr/tessdata_fast/blob/main/{}.traineddata'
> 
> TESSDATA_SCRIPT_URL = 'https://github.com/tesseract-ocr/tessdata_best/blob/main/{}.traineddata'
> ```
> now.

you can also download the traineddata file and put it to filepath as well.

**Comment by YeefyisOK** [comment]
For anyone hitting this: the 404 is Tesseract's `tessdata` download URL having moved. Two fixes that work — repoint videocr's `TESSDATA_URL` at the current `tessdata_fast` path, or just install the language data yourself (your distro's `tesseract-ocr-<lang>` package, or `brew install tesseract-lang` on Mac) so videocr never tries to fetch it.

Separately — if anyone lands here on a **Mac** and would rather skip the Python + Tesseract setup entirely, I've been using GeekLink, a native macOS app that OCRs burned-in subtitles into an SRT with nothing to install beyond the app: https://geeklink.dev/go/ocr — not a fix for videocr, just an option if you're on Mac and want the subtitles out without the toolchain.
