### ISSUE TITLE
Can't run Video CR in terminal

### ISSUE THREAD

**Issue by Vampyy97** [apm1467/videocr#51]
Getting below errors in video cr while running in terminal

(venv) Vampyy@Vampyys-Laptop desktop % python ~/Desktop/script_name.py
Traceback (most recent call last):
  File "/Users/Vampyy/Desktop/script_name.py", line 3, in <module>
    subtitles = get_subtitles('input.mp4', lang='eng')
  File "/Users/Vampyy/Desktop/venv/lib/python3.13/site-packages/videocr/api.py", line 8, in get_subtitles
    utils.download_lang_data(lang)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/Vampyy/Desktop/venv/lib/python3.13/site-packages/videocr/utils.py", line 21, in download_lang_data
    with urlopen(url) as res, open(filepath, 'w+b') as f:
         ~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
(venv) Vampyy@Vampyys-Laptop desktop %

**Comment by aetta** [comment]
Howdy! ~ You may need to manually update the constants.py ...here's the [workaround/fix](https://github.com/apm1467/videocr/issues/36#issuecomment-968286467)
